name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Check gomod consistency
      run: |
        make gomod
        if ! git diff --exit-code; then
          echo "go module is not consistent: run make gomod and commit results" >&2
          exit 1
        fi

    - name: Lint & build
      run: make ci

    - name: Test
      run: go test ./...
